const translations={
  it:{
    "nav.services":"Servizi","nav.about":"Chi siamo","nav.contact":"Contatti","nav.cta":"Contattaci","hero.eyebrow":"AUTOMOTIVE · PRAVISDOMINI","hero.lead":"Tutto per l’automobile, in un unico posto.","hero.copy":"Noleggio, vendita, trasporto merci, soccorso stradale, autofficina, autoricambi e gommista. Un partner unico per ogni esigenza.","hero.services":"Scopri i servizi","hero.quote":"Richiedi informazioni","facts.services":"SERVIZI INTEGRATI","facts.contacts":"NUMERI DIRETTI","facts.partner":"PARTNER UNICO","facts.location":"SEDE A PRAVISDOMINI","services.kicker":"SERVIZI","services.title":"I nostri servizi","services.intro":"Sette specialità, un solo partner. Soluzioni complete per te e per la tua automobile.","services.cta":"Parliamo della tua esigenza","service.rental":"Noleggio","service.sales":"Vendita auto","service.transport":"Trasporto merci","service.roadside":"Soccorso stradale","service.workshop":"Autofficina","service.parts":"Autoricambi","service.tyres":"Gommista","about.kicker":"NEWTON AUTOSERVICE","about.title":"Una risposta completa per la tua mobilità.","about.copy":"Newton riunisce servizi automotive e trasporto in un unico punto di riferimento a Pravisdomini. Un contatto semplice, soluzioni coordinate e attenzione concreta alle tue necessità.","about.one":"Servizi per privati, professionisti e imprese","about.two":"Assistenza chiara e diretta","about.three":"Sette competenze, un solo partner","about.link":"Contatta Newton","contact.kicker":"CONTATTI","contact.title":"Parliamo della tua esigenza.","contact.copy":"Chiamaci, scrivici su WhatsApp o vieni a trovarci a Pravisdomini.","contact.addressLabel":"INDIRIZZO","contact.primary":"NUMERO PRINCIPALE E WHATSAPP","contact.info":"INFORMAZIONI","contact.whatsapp":"Scrivici su WhatsApp","contact.call":"Chiama ora","footer.copy":"Servizi automotive e trasporto a Pravisdomini.","dialog.call":"Chiamaci"
  },
  en:{
    "nav.services":"Services","nav.about":"About us","nav.contact":"Contact","nav.cta":"Contact us","hero.eyebrow":"AUTOMOTIVE · PRAVISDOMINI","hero.lead":"Everything for your vehicle, all in one place.","hero.copy":"Rental, vehicle sales, freight transport, roadside assistance, workshop, spare parts and tyre services. One partner for every need.","hero.services":"Explore services","hero.quote":"Request information","facts.services":"INTEGRATED SERVICES","facts.contacts":"DIRECT NUMBERS","facts.partner":"SINGLE PARTNER","facts.location":"BASED IN PRAVISDOMINI","services.kicker":"SERVICES","services.title":"Our services","services.intro":"Seven specialities, one partner. Complete solutions for you and your vehicle.","services.cta":"Tell us what you need","service.rental":"Vehicle rental","service.sales":"Vehicle sales","service.transport":"Freight transport","service.roadside":"Roadside assistance","service.workshop":"Workshop","service.parts":"Spare parts","service.tyres":"Tyre service","about.kicker":"NEWTON AUTOSERVICE","about.title":"One complete answer for your mobility.","about.copy":"Newton brings automotive and transport services together at one trusted location in Pravisdomini. A simple point of contact, coordinated solutions and genuine attention to your needs.","about.one":"Services for individuals, professionals and businesses","about.two":"Clear, direct assistance","about.three":"Seven areas of expertise, one partner","about.link":"Contact Newton","contact.kicker":"CONTACT","contact.title":"Let’s talk about what you need.","contact.copy":"Call us, message us on WhatsApp or visit us in Pravisdomini.","contact.addressLabel":"ADDRESS","contact.primary":"PRIMARY NUMBER & WHATSAPP","contact.info":"INFORMATION","contact.whatsapp":"Message us on WhatsApp","contact.call":"Call now","footer.copy":"Automotive and transport services in Pravisdomini.","dialog.call":"Call us"
  }
};
const serviceText={
  rental:{it:["Noleggio","Soluzioni di mobilità flessibili per privati, professionisti e aziende. Contattaci per disponibilità e condizioni."],en:["Vehicle rental","Flexible mobility solutions for individuals, professionals and businesses. Contact us for availability and terms."]},
  sales:{it:["Vendita auto","Veicoli selezionati e supporto diretto durante la scelta e l’acquisto."],en:["Vehicle sales","Selected vehicles and direct support throughout the selection and purchase process."]},
  transport:{it:["Trasporto merci","Soluzioni di trasporto merci per imprese e professionisti, organizzate in base alle necessità."],en:["Freight transport","Freight transport solutions for companies and professionals, organised around your needs."]},
  roadside:{it:["Soccorso stradale","Assistenza quando un imprevisto ferma il tuo viaggio. Chiamaci per richiedere supporto."],en:["Roadside assistance","Help when an unexpected problem stops your journey. Call us to request support."]},
  workshop:{it:["Autofficina","Manutenzione, controlli e interventi per mantenere il veicolo efficiente e sicuro."],en:["Workshop","Maintenance, inspections and repairs to keep your vehicle efficient and safe."]},
  parts:{it:["Autoricambi","Ricambi e componenti per le diverse esigenze del tuo veicolo. Contattaci per una verifica."],en:["Spare parts","Parts and components for different vehicle needs. Contact us to check availability."]},
  tyres:{it:["Gommista","Servizi pneumatici per sicurezza, aderenza e controllo su strada."],en:["Tyre service","Tyre services for safety, grip and control on the road."]}
};
let language=localStorage.getItem('newton-language')||'it';
function applyLanguage(lang){language=lang;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const t=translations[lang][el.dataset.i18n];if(t)el.textContent=t});document.getElementById('lang-label').textContent=lang==='it'?'EN':'IT';document.title=lang==='it'?"Newton Autoservice | Servizi automotive a Pravisdomini":"Newton Autoservice | Automotive services in Pravisdomini";localStorage.setItem('newton-language',lang)}
document.querySelector('.language-switch').addEventListener('click',()=>applyLanguage(language==='it'?'en':'it'));
const menu=document.querySelector('.main-nav'),toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
const dialog=document.getElementById('service-dialog');document.querySelectorAll('.service-card').forEach(card=>card.addEventListener('click',()=>{const text=serviceText[card.dataset.service][language];document.getElementById('dialog-title').textContent=text[0];document.getElementById('dialog-copy').textContent=text[1];dialog.showModal();document.body.classList.add('locked')}));
function closeDialog(){dialog.close();document.body.classList.remove('locked')}document.querySelector('.dialog-close').addEventListener('click',closeDialog);dialog.addEventListener('click',e=>{if(e.target===dialog)closeDialog()});
document.getElementById('year').textContent=new Date().getFullYear();applyLanguage(language);
